# Generated by Django 4.1 on 2023-02-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_remove_todos_text_todos_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
