# Generated by Django 4.1 on 2023-02-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_todos_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('private', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=45)),
                ('content', models.TextField(max_length=245)),
                ('slug', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
